### PR TITLE
Fixes #21

### LINKED ISSUE #21: ValueError: ("the use of non-builtin globals isn't supported")
Getting below error. please help me out to proceed further.

(workvenv) bash-3.2$ pytest tests/ --cloud-node=hah@1.2.3.4 --cloud-chdir=/home/hah --cloud-max-processes=2 --rsyncdir=.
Detected root dir: /Users/harish/Work/PPMPro/automation
Detecting connectable test nodes...
NODES LEN 1
SPECS ssh=hah@1.2.3.4//id=1.2.3.4//chdir=/home/hah//python=python3.7
group 0
Node hah@1.2.3.4
HOST IS hah@1.2.3.4
Host 1.2.3.4
Found 1 connectable test nodes: {'hah@1.2.3.4'}
RSyncing directory structure
**rsync: -arHAXx: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(1337) [client=2.6.9]
RSync finished**

Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 340, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 312, in get_nodes_specs
    for node, hst in node_specs))
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 312, in <genexpr>
    for node, hst in node_specs))
KeyError: '1.2.3.4'

### PR DESCRIPTION
**Pull request by dasm**
ValueError: ("the use of non-builtin globals isn't supported")

Due to differences between `venv` and `virtualenv`, recommended is
latter.

Fully dropped support for Python 2.7.
Added explicit requirement for virtualenv.

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-cloud/22)

### CODE REVIEW

**Comment by dasm** [comment]
@hah86 I believe this PR should be solving your problems.
Please give it a look, and see if this is working for you.

**Review by bubenkoff — APPROVED** [review]
thank you very much!

**Comment by hah86** [comment]
> @hah86 I believe this PR should be solving your problems.
> Please give it a look, and see if this is working for you.

Thanks a lot.. Will check and get back in case of issues

**Comment by bubenkoff** [comment]
@dasm can you please add some py3 tests so we're sure it doesn't happen in the future, thanks

**Pull request merged**
