### PR TITLE
Ensure compat with xdist 2.0+

### LINKED ISSUE #17: Upcoming incompatibility in pytest-xdist 2.0: "slave" aliases removed
Hi!

As per https://github.com/pytest-dev/pytest-xdist/pull/541, pytest-xdist 2.0 will remove the deprecated "slave" 
aliases, which have been replaced by "worker" since pytest-xdist 1.22.

To avoid breakage, the team suggests to update your package to use the new terms, and make a new release to avoid sudden breakages once pytest-xdist 2.0 is released.

cc @Zac-HD @RonnyPfannschmidt

Thanks!

### PR DESCRIPTION
**Pull request by Zac-HD**
Fixes #17; see https://github.com/pytest-dev/pytest-xdist/pull/541 for background.

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-cloud/18)

### CODE REVIEW

**Review by bubenkoff — CHANGES_REQUESTED** [review]
please bump the version requirement for xdist accordingly
also, this should be a major release
and when you add a changelog record, don't assume the release already, this IMO should be done as part of the release process, so we keep unreleased changes under Unreleased instead of the number

**Comment by Zac-HD** [comment]
This is compatible back to `pytest-xdist` 1.22.3, which is older than the current minimum requirement :slightly_smiling_face: 

It's therefore an entirely internal change - this is an implementation detail which doesn't change any public API or dependencies, just ensures that users can upgrade `pytest-xdist` without breaking `pytest-cloud`.

**Comment by bubenkoff** [comment]
@Zac-HD then why the tests didn't fail before? then we should make sure that it's covered

**Comment by Zac-HD** [comment]
The new version of xdist hasn't been released yet - I'm aiming to update all the major integrations first.

And it's definitely covered, we're just switching to use the newer of two identical attributes before the old one is removed - so it's a no-op change on current versions but will not break when the next version comes out.

**Comment by Zac-HD** [comment]
@bubenkoff - I've fixed the changelog to list this as "Unreleased".  If there's anything else I need to do before you can merge this, please let me know!  

It's working at the moment but without this backwards-compatible patch `pytest-cloud` will break as soon as `pytest-xdist` 2 is released 😕

**Review by bubenkoff — APPROVED** [review]

**Comment by bubenkoff** [comment]
please merge with squashing
would you like to get the pypi permission to release it yourself, now and in the future?

**Comment by Zac-HD** [comment]
Thanks @bubenkoff!

While I appreciate the offer, I'm happy to leave the release process to someone more regularly involved.  Personally I like to automate releases entirely, so that CI tries a `twine upload` if the build passes on `master`, so I'm seriously out of practice at any manual release process :sweat_smile:

**Comment by bubenkoff** [comment]
@Zac-HD if you're willing to help, let's automate it for this project?

**Comment by bubenkoff** [comment]
5.0.0 is out

**Comment by Zac-HD** [comment]
It's pretty easy!  For `hypothesis-jsonschema`, [here's the logic](https://github.com/Zac-HD/hypothesis-jsonschema/blob/e16783190045b530ca4db43eefe0da8a5cf57e8f/.github/workflows/ci.yml#L42-L58):

```bash
# to run in CI, on master, if tests pass:
python -m pip install --upgrade pip setuptools wheel twine
python setup.py sdist bdist_wheel && twine upload --skip-existing dist/*
```

And I wrote some tests to check that the version number and changelog are up to date too: https://github.com/Zac-HD/hypothesis-jsonschema/blob/master/tests/test_version.py

**Comment by bubenkoff** [comment]
@Zac-HD great, are you interested in helping set it up?

**Pull request merged**
