### PR TITLE
Removed pytest fixed version. Improved mocking in the test.

### LINKED ISSUE #3: Can the version dependency be removed?
Currently the version of the pytest is <2.8.0
It is a bit outdated. Is there any particular reason for this limitation? The latest pytest version is 2.9.0

### PR DESCRIPTION
**Pull request by olegpidsadnyi**
Fixes #3

---

This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-cloud/5)

### CODE REVIEW

**Comment by bubenkoff** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[CHANGES.rst, line 8 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSirRU5VSCXn1UatI7:-KDSirRU5VSCXn1UatI8:660993915) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/CHANGES.rst#L8)):_
worth a major version update, because we loose the compartibility with the older pytest, so the version can be 2.0.0

---

_[setup.py, line 30 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSj3z2CGClcVmhsnn4:-KDSj3z2CGClcVmhsnn5:-1907390052) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/setup.py#L30)):_
have a minimum requirement now, as we've dropped pytest-cache dep

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSjANOKTzRIL7NmIz0:-KDSjANPbDK8xKfMosW2:-1054325896) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/setup.py#L32)):_
remove!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5)_

**Comment by olegpidsadnyi** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

_[CHANGES.rst, line 8 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSirRU5VSCXn1UatI7:-KDSoT3o_eLpXaTpE7_I:-499146009) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/CHANGES.rst#L8)):_
Done.

---

_[setup.py, line 30 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSj3z2CGClcVmhsnn4:-KDSoUWfurCPC2zj7M_f:-499146009) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/setup.py#L30)):_
Done.

---

_[setup.py, line 32 [r1]](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5#-KDSjANOKTzRIL7NmIz0:-KDSoV0p_JKAbZS3Lski:-499146009) ([raw file](https://github.com/pytest-dev/pytest-cloud/blob/073884f112bf528fa18f9a7c8ebc11e6871253a7/setup.py#L32)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5)_

**Comment by bubenkoff** [comment]
Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pytest-dev/pytest-cloud/5)_

**Comment by bubenkoff** [comment]
please release yourself (you should have the perms to do it)

**Pull request merged**
